server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
app:
  config:
    keycloak:
      url: http://localhost:8080/auth
      realm: banking-realm
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
      - id: fund-transfer-service
        uri: lb://fund-transfer-service
        predicates:
        - Path=/fund-transfer/**
        filters:
        - StripPrefix=1
      - id: core-banking-service
        uri: lb://core-banking-service
        predicates:
        - Path=/banking-core/**
        filters:
        - StripPrefix=1
      - id: utility-payment-service
        uri: lb://utility-payment-service
        predicates:
        - Path=/utility-payment/**
        filters:
        - StripPrefix=1
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          banking-client:
            provider: keycloak
            client-id: banking-client
            client-secret: 73ed8403-a9f0-47d6-8c08-ab48100cb2b2
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs